image: gradle:jdk12

pipelines:
  branches:
    dev:
      - step:
          name: deploy:snapshot
          caches:
            - gradle
          script:
            - bash ./gradlew --build-cache assemble
            - bash ./gradlew publish
    feature/*:
      - step:
          name: deploy:feature
          caches:
            - gradle
          script:
            - bash ./gradlew --build-cache assemble
            - bash ./gradlew publish
    bugfix/*:
      - step:
          name: deploy:bugfix
          caches:
            - gradle
          script:
            - bash ./gradlew --build-cache assemble
            - bash ./gradlew publish
    master:
      - step:
          name: sonar:snapshot
          caches:
            - gradle
          script:
            - bash ./gradlew sonarqube -Dsonar.projectKey=LegendServiceRegistry -Dsonar.host.url=https://sonar.playlegend.dev -Dsonar.login=f087a06b40faf9da823e1db6388d07fefae8f115
  tags:
    '*.*.*':
      - step:
          name: deploy:release
          caches:
            - gradle
          script:
            - bash ./gradlew --build-cache assemble
            - bash ./gradlew publish