image: gradle:jdk12

pipelines:
  branches:
    dev:
      - step:
          name: deploy:snapshot
          caches:
            - gradle
          script:
            - bash ./gradlew --build-cache assemble
            - bash ./gradlew publish
    feature/*:
      - step:
          name: deploy:feature
          caches:
            - gradle
          script:
            - bash ./gradlew --build-cache assemble
            - bash ./gradlew publish
    bugfix/*:
      - step:
          name: deploy:bugfix
          caches:
            - gradle
          script:
            - bash ./gradlew --build-cache assemble
            - bash ./gradlew publish
  tags:
    '*.*.*':
      - step:
          name: deploy:release
          caches:
            - gradle
          script:
            - bash ./gradlew --build-cache assemble
            - bash ./gradlew publish