name: Static code analyis
on:
  push:
    branches:
      - master
      - dev
      - feature/*
      - bugfix/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: 'Checkout repository on branch: ${{ steps.extract_branch.outputs.branch }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew --build-cache assemble
        env:
          repositoryUser: ${{ secrets.repositoryUser }}
          repositoryPassword: ${{ secrets.repositoryPassword }}
      - name: 'Run an analysis of the ${{ steps.extract_branch.outputs.branch }} branch'
        run: ./gradlew sonarqube -Dsonar.projectKey=${{ secrets.sonarProject }} -Dsonar.host.url=https://sonar.playlegend.net -Dsonar.login=${{ secrets.sonarToken }} -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }} -Dsonar.projectVersion=${{ steps.extract_branch.outputs.branch }}
